CREATE DATABASE PV_521_DDL
ON
(
	NAME		=	PV_521_DDL,
	FILENAME	=	'C:\MSSQL\PV_521.mdf',
	SIZE		=	  8 MB,
	MAXSIZE		=	500 MB,
	FILEGROWTH	=	  8 MB
)
LOG ON
(
	NAME		=	PV_521_DDL_log,
	FILENAME	=	'C:\MSSQL\PV_521_DDL.ldf',
	SIZE		=	  8 MB,
	MAXSIZE		=	500 MB,
	FILEGROWTH	=	  8 MB
)